services:
  - type: web
    name: paytonbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'webhook:app' --bind=0.0.0.0:$PORT --timeout 120 --worker-class gthread --threads 4
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PAYMENT_PROVIDER_TOKEN
        sync: false  # Будет установлено в панели управления Render 